services:
  - type: web
    name: aranoz
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:iAyr1itCkKQXwyDXZnATT9ElJgQAzaT+DQR+Dvyir4A=
      - key: APP_DEBUG
        value: true
      - key: DB_CONNECTION
        value: pgsql
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_DRIVER
        value: array